name: BigBrother
version: <VERSION>
api: [3.0.0-ALPHA11]
description: "Allows the connection of Minecraft: PC clients to PocketMine-MP servers"
authors:
  - BigBrotherTeam
website: https://github.com/BigBrotherTeam/BigBrother
load: STARTUP
main: shoghicp\BigBrother\BigBrother
